name: Basic Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest

  steps:
  
    - name: Run local k6 test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: src/tests/script.js